### ISSUE TITLE
Fill README.MD with some helpful content

### ISSUE THREAD

**Issue by heubeck** [kunzese/gke-exporter#49]

**Comment by kunzese** [comment]
@heubeck thanks for the issue. Can you have look at #50 and tell me what you think?

**Comment by heubeck** [comment]
I think you should add a little sentence "what does this exporter and how do the resulting metrics look".
The rest ist quite nice, thank you.

**Comment by kunzese** [comment]
I added a description and some examples. Could please have a look at #50 again?
